---
 - name: Create a Subnet
   azure_rm_subnet:
     resource_group: "{{ resource_group_name }}"
     name: "{{ subnet_name }}"
     address_prefix: "{{ subnet_cidr }}"
     virtual_network: "{{ vnet_name }}"

